---
- hosts: all
#  remote_user: root
  gather_facts: false
  roles:
    - python-role
    - required-role

#- name: Installing missing packages on managed
#  hosts: all
#  tasks:
#  - name: Installing missing sudo, procps, nano, unzip
#    ansible.builtin.package:
#      name:
#        - sudo
#        - procps
#        - nano
#        - unzip
#        - curl
#      state: present

- name: Installing Lighthouse, Nginx
  hosts: lighthouse-01
  roles:
    - nginx-role
    - lighthouse-role

- name: Install Clickhouse
  hosts: clickhouse-01
  roles:
    - clickhouse-role

- name: Install Vector
  hosts: vector-01
  roles:
    - role: vector-role
