---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: ch
      ansible_connection: docker 

vector:
  hosts:
    vector-01:
      ansible_host: vec
      ansible_connection: docker

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: lh
      ansible_connection: docker

#    debian:
#      ansible_host: debian
#      ansible_connection: docker
